[green_agent]
agentbeats_id = "019b7d0e-2674-79f0-80ab-d2af5c870794"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO", USE_OPEN_ROUTER="TRUE", OPEN_ROUTER_API_KEY="${OPEN_ROUTER_API_KEY}" }

[[participants]]
agentbeats_id = "019bbbaf-f3ff-7ff2-903d-e5ba90bdf1d9"
name = "agent"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", "MODEL" = "gemini-3-flash-preview" }

[config]
# Add your assessment config here
num_maps = 25
top_k = 5

