[green_agent]
agentbeats_id = "019b7d0e-2674-79f0-80ab-d2af5c870794"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO", USE_OPEN_ROUTER="TRUE", OPEN_ROUTER_API_KEY="${OPEN_ROUTER_API_KEY}", TEMPERATURE="0.0" }

[[participants]]
name = "agent"
agentbeats_id = "019bc243-c093-7de1-b3cd-f5968afbfdeb"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", "MODEL" = "gemini-2.5-pro" } 

[config]
jar_output_dir = "/app/outputs"
# Add your assessment config here
num_maps = 5
top_k = 5

