[green_agent]
agentbeats_id = "019b7d0e-2674-79f0-80ab-d2af5c870794"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", LOG_LEVEL = "INFO", USE_OPEN_ROUTER="TRUE", OPEN_ROUTER_API_KEY="${OPEN_ROUTER_API_KEY}" }

[[participants]]
agentbeats_id = "019ba22d-08a2-7c90-84a9-026bc953a53f"
name = "agent"
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", "MODEL" = "gemini-2.5-pro" }

[config]
# Add your assessment config here
num_maps = 1
top_k = 5

